package constant

const (
	YES = "YES"
	NO  = "NO"

	// Loan Pack status
	LOAN_PACK_ACTIVE   = "ACTIVE"
	LOAN_PACK_INACTIVE = "INACTIVE"

	// RD Pack status
	RD_PACK_ACTIVE   = "ACTIVE"
	RD_PACK_INACTIVE = "INACTIVE"

	// FD Pack status
	FD_PACK_ACTIVE   = "ACTIVE"
	FD_PACK_INACTIVE = "INACTIVE"

	// Pigmy Pack Status
	PIGMY_PACK_ACTIVE   = "ACTIVE"
	PIGMY_PACK_INACTIVE = "INACTIVE"

	//Customer status
	CUST_ACTIVE   = "ACTIVE"
	CUST_INACTIVE = "INACTIVE"

	// Loan status
	LOAN_REGULAR     = "REGULAR"
	LOAN_GRACEPERIOD = "GRACEPERIOD"
	LOAN_IRREGULAR   = "IRREGULAR"
	LOAN_INACTIVE    = "INACTIVE"
	LOAN_CLOSED      = "CLOSED"

	// RD status
	RD_ACTIVE   = "ACTIVE"
	RD_INACTIVE = "INACTIVE"
	RD_HOLD     = "HOLD"
	RD_CLOSED   = "CLOSED"

	// FD status
	FD_ACTIVE   = "ACTIVE"
	FD_INACTIVE = "INACTIVE"
	FD_HOLD     = "HOLD"
	FD_CLOSED   = "CLOSED"

	// Pigmy status
	PIGMY_ACTIVE      = "ACTIVE"
	PIGMY_INACTIVE    = "INACTIVE"
	PIGMY_HAS_LOAN    = "HAS_LOAN"
	PIGMY_LOAN_CLOSED = "LOAN_CLOSED"
	PIGMY_CLOSED      = "CLOSED"
)
